# Generated by Django 4.0.3 on 2022-03-31 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_permission_role_systemadmingroup_systemadmin_and_more'),
        ('commons', '0002_periodicity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='BankPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='cash acceptor bank name')),
                ('bank_branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('txn_reference_number', models.CharField(max_length=50, verbose_name='transaction reference name')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.city')),
                ('bank_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.country')),
                ('bank_region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.region')),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='coupon code')),
                ('initial_value', models.FloatField(default=0.0, verbose_name='initial coupon value')),
                ('current_value', models.FloatField(default=0.0, verbose_name='current coupon value')),
                ('redeemed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='redemption date')),
                ('expire_on', models.DateTimeField(verbose_name='expire date')),
            ],
        ),
        migrations.CreateModel(
            name='MobilePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_app_name', models.CharField(max_length=50)),
                ('txn_reference_number', models.CharField(max_length=50, verbose_name='transaction reference number')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.FloatField(default=0.0, verbose_name='total price to be paid')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='paid amount')),
                ('narative', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentApprovalMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(default='MANUAL', max_length=20, verbose_name='Payment approval mode')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Payment method name')),
                ('description', models.TextField(blank=True, null=True)),
                ('approval_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentapprovalmode', verbose_name='Payment method name')),
            ],
        ),
        migrations.CreateModel(
            name='SupportedCardScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=50, verbose_name='card scheme name')),
                ('BIN', models.CharField(max_length=10, verbose_name='card BIN')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethodDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.FloatField(default=0.0, verbose_name='discount in percent')),
                ('discount_fixed', models.FloatField(default=0.0, verbose_name='discount amount discount')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date added')),
                ('start_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='date discount starts')),
                ('expire_on', models.DateTimeField(editable=False, verbose_name='date discount expires')),
                ('narative', models.TextField(blank=True, null=True)),
                ('payment_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentByMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0, verbose_name='payment amount using this method')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentmethod', verbose_name='payment method')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='parent payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ManyToManyField(through='payments.PaymentByMethod', to='payments.paymentmethod', verbose_name='payment method used'),
        ),
        migrations.CreateModel(
            name='MobilePayReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept', models.FileField(upload_to=payments.models.get_mobile_reciept_file_path, verbose_name='mobile reciept path')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mobile_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.mobilepayment')),
            ],
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='parent_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='parent payment record'),
        ),
        migrations.CreateModel(
            name='CreditCardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_reference_number', models.CharField(max_length=50, verbose_name='transaction reference number')),
                ('card_holder_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='card holder name')),
                ('card_last_4_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=100, null=True, verbose_name='card issuer bank name')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('card_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_payment', to='payments.supportedcardscheme', verbose_name='parent card scheme')),
                ('parent_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='parent payment record')),
            ],
        ),
        migrations.CreateModel(
            name='CouponPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField(default=0.0, verbose_name='paid_amount')),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='payment date')),
                ('coupon', models.ManyToManyField(through='payments.AppliedCoupon', to='payments.coupon')),
                ('parent_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='parent payment record')),
            ],
        ),
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_cash_amount', models.FloatField(default=0.0)),
                ('recieved_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('cash_reciever_admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.systemadmin')),
                ('parent_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='parent payment record')),
            ],
        ),
        migrations.CreateModel(
            name='BankReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reciept', models.FileField(upload_to=payments.models.get_bank_reciept_file_path, verbose_name='bank reciept path')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('bank_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.bankpayment')),
            ],
        ),
        migrations.AddField(
            model_name='bankpayment',
            name='parent_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment', verbose_name='parent payment record'),
        ),
        migrations.AddField(
            model_name='appliedcoupon',
            name='coupon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.coupon'),
        ),
        migrations.AddField(
            model_name='appliedcoupon',
            name='coupon_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.couponpayment'),
        ),
    ]
