# Generated by Django 4.0.3 on 2022-06-09 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='narative',
            new_name='narrative',
        ),
    ]
