# Generated by Django 4.0.3 on 2022-06-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_narative_payment_narrative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankpayment',
            old_name='parent_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='bankpayment',
            old_name='txn_reference_number',
            new_name='transaction_ref_number',
        ),
        migrations.RenameField(
            model_name='cashpayment',
            old_name='parent_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='parent_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='creditcardpayment',
            old_name='txn_reference_number',
            new_name='transaction_ref_number',
        ),
        migrations.RenameField(
            model_name='mobilepayment',
            old_name='parent_payment',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='mobilepayment',
            old_name='txn_reference_number',
            new_name='transaction_ref_number',
        ),
        migrations.RemoveField(
            model_name='couponpayment',
            name='parent_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='payment',
            name='coupon_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.couponpayment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentmethod', verbose_name='payment method used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='coupon code'),
        ),
        migrations.DeleteModel(
            name='PaymentByMethod',
        ),
    ]
