# Generated by Django 4.0.3 on 2022-06-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_rename_method_payment_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponpayment',
            name='coupon',
        ),
        migrations.AddField(
            model_name='couponpayment',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.coupon'),
        ),
        migrations.DeleteModel(
            name='AppliedCoupon',
        ),
    ]
