# Generated by Django 4.0.3 on 2022-06-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_couponpayment_coupon_couponpayment_coupon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='pm_key',
            field=models.CharField(choices=[('PM01', 'Cash Payment'), ('PM02', 'Bank Transfer'), ('PM03', 'Credit Card'), ('PM04', 'Subscription'), ('PM05', 'Coupon Payment')], default='PM01', max_length=50, verbose_name='Payment method key'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='approval_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymentapprovalmode', verbose_name='Payment approval mode'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Payment method name'),
        ),
    ]
