# Generated by Django 4.0.3 on 2022-06-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentmethod_pm_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='pm_key',
            field=models.CharField(choices=[('PM01', 'Cash Payment'), ('PM02', 'Bank Transfer'), ('PM03', 'Credit Card'), ('PM04', 'Subscription'), ('PM05', 'Coupon Payment'), ('PM06', 'Mobile Payment')], default='PM01', max_length=50, verbose_name='Payment method key'),
        ),
    ]
