# Generated by Django 4.0.3 on 2022-06-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_alter_paymentmethod_pm_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='pm_key',
            field=models.CharField(choices=[('PM01', 'Cash Payment'), ('PM02', 'Bank Transfer'), ('PM03', 'Credit Card'), ('PM04', 'Subscription'), ('PM05', 'Coupon Payment'), ('PM06', 'Mobile Payment')], max_length=50, unique=True, verbose_name='Payment method key'),
        ),
    ]
