# Generated by Django 4.0.3 on 2022-06-19 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_paymentmethod_pm_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_amount',
        ),
    ]
