# Generated by Django 4.0.3 on 2022-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myhomeuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhomeuser',
            name='last_login',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
