# Generated by Django 4.0.3 on 2022-03-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myhomeuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhomeuser',
            name='user_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to='users.myhomeusergroup'),
        ),
    ]
