# Generated by Django 4.0.3 on 2022-03-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myhomeuser_user_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myhomeusergroup',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='user group'),
        ),
    ]
