# Generated by Django 4.0.3 on 2022-03-31 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myhomeusergroup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('permission', models.ManyToManyField(to='users.permission', verbose_name='permissions in this role')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdminGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('role', models.ManyToManyField(related_name='roles', to='users.role', verbose_name='roles in this group')),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_password', models.CharField(blank=True, max_length=30, null=True, verbose_name='Second password of the admin')),
                ('use_sec_pass_for_login', models.BooleanField(default=True, verbose_name='use second password for login?')),
                ('admin_group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.systemadmingroup')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='parent user')),
            ],
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_in_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('logged_out_on', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_historys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
