PM_CASH_PAYMENT = "PM01"
PM_BANK_TRANSFER = "PM02"
PM_CREDIT_CARD = "PM03"
PM_SUBSCRIPTION = "PM04"
PM_COUPON_PAYMENT = "PM05"
PM_MOBILE_PAYMENT = "PM06"

# PROPERTY CATEGORY KEYS
APARTMENT_KEY = "CAT001"
CONDOMINIUM_KEY = "CAT002"
TRADITIONAL_HOUSE_KEY = "CAT003"
VILLA_KEY = "CAT004"
SHARE_HOUSE_KEY = "CAT005"
COMMERCIAL_PROPERTY_KEY = "CAT006"
OFFICE_KEY = "CAT007"
HALL_KEY = "CAT008"
LAND_KEY = "CAT009"
ALL_PURPOSE_PROPERTY_KEY = "CAT010"


#LISTING TYPES
LISTING_STATE_ACTIVE = "ACTIVE"
LISTING_STATE_INACTIVE = "INACTIVE"
LISTING_STATE_UNAVAILABLE = "UNAVAILABLE"

#FEATURE LISTING PRICE STATE
FEATURE_PRICE_ACTIVE = "ACTIVE"
FEATURE_PRICE_INACTIVE = "INACTIVE"

#FEATURED LISTING  STATE
FEATURED_LISTING_ACTIVE = "ACTIVE"
FEATURED_LISTING_INACTIVE = "INACTIVE"
FEATURED_LISTING_EXPIRED = "EXPIRED"