# Generated by Django 4.0.3 on 2022-03-21 22:25

import agents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='agent name')),
                ('email', models.EmailField(max_length=254, verbose_name='contact email address')),
                ('contact_number', models.CharField(max_length=50, verbose_name='contact phone number')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True, verbose_name='agent slogan')),
                ('description', models.TextField()),
                ('registered_on', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commons.address')),
            ],
        ),
        migrations.CreateModel(
            name='AgentLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=agents.models.get_agent_logo_file_path, verbose_name='agent logo')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessagePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_out_in_app_message', models.BooleanField(blank=True, default=False)),
                ('opt_out_sms_message', models.BooleanField(blank=True, default=False)),
                ('opt_out_email_message', models.BooleanField(blank=True, default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='AgentAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='agent where admin works')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='logo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.agentlogo'),
        ),
        migrations.AddField(
            model_name='agent',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
