# Generated by Django 4.0.3 on 2022-03-21 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='country name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='country code')),
                ('latitute', models.CharField(max_length=20, verbose_name='geo latitude')),
                ('longitude', models.CharField(max_length=20, verbose_name='geo logitude')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='region name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='region code')),
                ('latitute', models.CharField(max_length=20, verbose_name='geo logitude')),
                ('longitude', models.CharField(max_length=20, verbose_name='geo logitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='commons.country', verbose_name='country of region')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='city name')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='city code')),
                ('latitute', models.CharField(max_length=20, verbose_name='geo latitued')),
                ('longitude', models.CharField(max_length=20, verbose_name='geo longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_cities', to='commons.country', verbose_name='country of city')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_cities', to='commons.region', verbose_name='region of city')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100, verbose_name='street name')),
                ('post_code', models.CharField(blank=True, max_length=20, null=True)),
                ('building_name_or_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='building name or number')),
                ('room_number', models.CharField(blank=True, max_length=20, null=True)),
                ('latitute', models.CharField(max_length=20, verbose_name='geo latitued')),
                ('longitude', models.CharField(max_length=20, verbose_name='geo longitude')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.country')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commons.region')),
            ],
        ),
    ]
