# Generated by Django 4.0.3 on 2022-03-31 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30, verbose_name='period label or name')),
                ('num_of_days', models.IntegerField(default=1, verbose_name='number of days in this period')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
