# Generated by Django 4.0.3 on 2022-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='latitute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo latitued'),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo longitude'),
        ),
        migrations.AlterField(
            model_name='city',
            name='latitute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo latitued'),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo longitude'),
        ),
        migrations.AlterField(
            model_name='country',
            name='latitute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo latitude'),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo logitude'),
        ),
        migrations.AlterField(
            model_name='region',
            name='latitute',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo logitude'),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo logitude'),
        ),
    ]
