# Generated by Django 4.0.3 on 2022-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0003_alter_address_latitute_alter_address_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='latitute',
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='geo latitude'),
        ),
    ]
