# Generated by Django 4.0.3 on 2022-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0006_alter_periodicity_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
