# Generated by Django 4.0.3 on 2022-06-08 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0040_rename_total_coumpound_area_villa_total_compound_area'),
        ('agents', '0004_agent_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedListingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True, verbose_name='featured listing state')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50, unique=True, verbose_name='listing state')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True, verbose_name='listing type')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.agent', verbose_name='agent who creates this listing')),
                ('listing_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_in_this_state', to='listings.listingstate')),
                ('listing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_in_this_type', to='listings.listingtype')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='payments.payment')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50, unique=True, verbose_name='payment mode')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VillaListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='villa_listing', to='listings.mainlisting')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.villa')),
            ],
        ),
        migrations.CreateModel(
            name='TraditionalHouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_house_listing', to='listings.mainlisting')),
                ('traditional_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.traditionalhouse')),
            ],
        ),
        migrations.CreateModel(
            name='ShareHouseListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('Share_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.sharehouse')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Share_house_listing', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('main_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.mainlisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OfficeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_listing', to='listings.mainlisting')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.office')),
            ],
        ),
        migrations.AddField(
            model_name='mainlisting',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_in_this_mode', to='listings.paymentmode'),
        ),
        migrations.AddField(
            model_name='mainlisting',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.property'),
        ),
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.land')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land_listing', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='HallListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.hall')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall_listing', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expire_on', models.DateTimeField()),
                ('feature_payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payments.payment')),
                ('featured_listing_state', models.ForeignKey(default='EXPIRED', on_delete=django.db.models.deletion.SET_DEFAULT, to='listings.featuredlistingstate')),
                ('main_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CondominiumListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('condominium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.condominium')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condominium_listing', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialPropertyUnitListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('commercial_property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.commercialpropertyunit')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_property_unit_listing', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='ApartmentUnitListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('apartment_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.apartmentunit')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_unit_listing', to='listings.mainlisting')),
            ],
        ),
        migrations.CreateModel(
            name='AllPurposePropertyUnitListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listed_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('all_purpose_property_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='properties.allpurposepropertyunit')),
                ('main_listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_purpose_property_unit_listing', to='listings.mainlisting')),
            ],
        ),
    ]
