# Generated by Django 4.0.3 on 2022-06-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlisting',
            name='payment_mode',
        ),
        migrations.DeleteModel(
            name='PaymentMode',
        ),
    ]
