# Generated by Django 4.0.3 on 2022-06-09 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_mainlisting_payment_mode_delete_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=50, unique=True, verbose_name='payment mode')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mainlisting',
            name='listing_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings_in_this_mode', to='listings.listingmode'),
        ),
    ]
