# Generated by Django 4.0.3 on 2022-06-09 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingmode_mainlisting_listing_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainlisting',
            name='listing_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings_in_this_mode', to='listings.listingmode'),
        ),
    ]
