# Generated by Django 4.0.3 on 2022-06-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_mainlisting_deposit_in_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainlisting',
            name='listing_mode',
        ),
        migrations.RemoveField(
            model_name='mainlisting',
            name='listing_state',
        ),
        migrations.AddField(
            model_name='mainlisting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
