# Generated by Django 4.0.3 on 2022-06-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_remove_mainlisting_listing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlisting',
            name='listing_mode',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Subscription'), ('PAY_PER_LISTING', 'Pay-per-listing')], default='PAY_PER_LISTING', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mainlisting',
            name='listing_state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='INACTIVE', max_length=50),
        ),
    ]
