# Generated by Django 4.0.3 on 2022-06-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_mainlisting_listing_mode_mainlisting_listing_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlisting',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainlisting',
            name='listing_state',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNAVAILABLE', 'Unavailable')], default='INACTIVE', max_length=50),
        ),
    ]
