# Generated by Django 4.0.3 on 2022-06-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_alter_listingdiscountbycategory_param_value'),
        ('listings', '0009_mainlisting_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialpropertyunitlisting',
            name='commercial_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_listings', to='properties.commercialproperty'),
            preserve_default=False,
        ),
    ]
