# Generated by Django 4.0.3 on 2022-06-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_alter_listingdiscountbycategory_param_value'),
        ('listings', '0010_commercialpropertyunitlisting_commercial_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartmentunitlisting',
            name='apartment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_listings', to='properties.apartment'),
            preserve_default=False,
        ),
    ]
