# Generated by Django 4.0.3 on 2022-06-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0050_alter_listingdiscountbycategory_param_value'),
        ('listings', '0011_apartmentunitlisting_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpurposepropertyunitlisting',
            name='all_purpose_property',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='unit_listings', to='properties.allpurposeproperty'),
            preserve_default=False,
        ),
    ]
