# Generated by Django 4.0.3 on 2022-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_mainlisting_listing_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainlisting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
