# Generated by Django 4.0.3 on 2022-07-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_mainlisting_description'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='savedlisting',
            constraint=models.UniqueConstraint(fields=('main_listing', 'user'), name='unique_saved_listing_per_user_constraint'),
        ),
    ]
