# Generated by Django 4.0.3 on 2022-08-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_featureprice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredlisting',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
