# Generated by Django 4.0.3 on 2023-02-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_featuredlisting_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingmode',
            name='mode',
            field=models.CharField(max_length=56, unique=True, verbose_name='payment mode'),
        ),
    ]
