# Generated by Django 4.0.3 on 2022-03-31 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_amenitycategory_apartment_buildingtype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('property_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='properties.property')),
                ('storey', models.IntegerField(default=0, verbose_name='Hall storey level')),
                ('number_of_seats', models.IntegerField(default=5, verbose_name='how many seats it has?')),
                ('total_capacity', models.IntegerField(default=5, verbose_name='total capacity including standing')),
                ('hall_description', models.TextField()),
            ],
            bases=('properties.property',),
        ),
    ]
