# Generated by Django 4.0.3 on 2022-05-04 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_apartment_is_multi_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='condominium',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='office',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='traditionalhome',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='versatilepropertyunit',
            name='storey',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='storey',
        ),
        migrations.AddField(
            model_name='apartment',
            name='floors',
            field=models.IntegerField(default=0, verbose_name='apartment number of floors'),
        ),
        migrations.AddField(
            model_name='apartmentunit',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='commercial property floor level'),
        ),
        migrations.AddField(
            model_name='condominium',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='condominium floor level'),
        ),
        migrations.AddField(
            model_name='hall',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Hall floor level'),
        ),
        migrations.AddField(
            model_name='office',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='office floor level'),
        ),
        migrations.AddField(
            model_name='traditionalhome',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='Home floor level'),
        ),
        migrations.AddField(
            model_name='versatilepropertyunit',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='versatile unit floor level'),
        ),
        migrations.AddField(
            model_name='villa',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='How many floor it has'),
        ),
    ]
