# Generated by Django 4.0.3 on 2022-05-09 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import properties.models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_propertyarealabel_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVirtualTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_video', models.FileField(upload_to=properties.models.get_property_virtual_file_name, verbose_name='property virtual video')),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.DeleteModel(
            name='PropertyVirtualVideo',
        ),
    ]
