# Generated by Django 4.0.3 on 2022-05-10 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyvirtualtour_alter_propertyvideo_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertycategory',
            name='cat_key',
            field=models.CharField(choices=[('CAT001', 'Apartment'), ('CAT002', 'Condominium'), ('CAT003', 'Traditional House'), ('CAT004', 'Villa'), ('CAT005', 'Commercial Property'), ('CAT006', 'Hall'), ('CAT007', 'Land')], default='CAT001', max_length=20, unique=True, verbose_name='category key'),
        ),
    ]
