# Generated by Django 4.0.3 on 2022-05-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertycategory_cat_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Point_of_interest',
            field=models.ManyToManyField(blank=True, related_name='poi_near_by_properties', through='properties.PropertyPOI', to='properties.pointofinterest'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TransportFacility',
            field=models.ManyToManyField(blank=True, related_name='tran_near_by_properties', through='properties.PropertyTransFacility', to='properties.transportfacility'),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenity',
            field=models.ManyToManyField(blank=True, related_name='linked_properties', to='properties.amenity'),
        ),
        migrations.AlterField(
            model_name='property',
            name='education_facility',
            field=models.ManyToManyField(blank=True, related_name='edu_near_by_properties', through='properties.PropertyEduFacility', to='properties.educationfacility'),
        ),
    ]
