# Generated by Django 4.0.3 on 2022-05-10 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_property_point_of_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='apartmentunit',
            name='apartment',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='commercialproperty',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='commercialpropertyunit',
            name='commercial_property',
        ),
        migrations.RemoveField(
            model_name='condominium',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='hall',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='land',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='office',
            name='building_type',
        ),
        migrations.RemoveField(
            model_name='office',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='traditionalhome',
            name='property_ptr',
        ),
        migrations.RemoveField(
            model_name='versatileproperty',
            name='best_category_for',
        ),
        migrations.RemoveField(
            model_name='versatileproperty',
            name='property_ptr',
        ),
        migrations.DeleteModel(
            name='VersatilePropertyUnit',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='property_ptr',
        ),
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='ApartmentUnit',
        ),
        migrations.DeleteModel(
            name='CommercialProperty',
        ),
        migrations.DeleteModel(
            name='CommercialPropertyUnit',
        ),
        migrations.DeleteModel(
            name='Condominium',
        ),
        migrations.DeleteModel(
            name='Hall',
        ),
        migrations.DeleteModel(
            name='Land',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
        migrations.DeleteModel(
            name='TraditionalHome',
        ),
        migrations.DeleteModel(
            name='VersatileProperty',
        ),
        migrations.DeleteModel(
            name='Villa',
        ),
    ]
