# Generated by Django 4.0.3 on 2022-05-11 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_alter_propertycategory_cat_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='condominium',
            old_name='num_of_baths',
            new_name='number_of_baths',
        ),
        migrations.RenameField(
            model_name='traditionalhouse',
            old_name='num_of_baths',
            new_name='number_of_baths',
        ),
        migrations.RenameField(
            model_name='villa',
            old_name='num_of_baths',
            new_name='number_of_baths',
        ),
    ]
