# Generated by Django 4.0.3 on 2022-05-11 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0014_rename_num_of_baths_condominium_number_of_baths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpurposeproperty',
            name='building_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_purpose_properties', to='properties.buildingtype', verbose_name='all purpose property building type'),
        ),
        migrations.AlterField(
            model_name='propertycategory',
            name='cat_key',
            field=models.CharField(choices=[('CAT001', 'Apartment'), ('CAT002', 'Condominium'), ('CAT003', 'Traditional House'), ('CAT004', 'Villa'), ('CAT005', 'Share House'), ('CAT006', 'Commercial Property'), ('CAT007', 'Office'), ('CAT008', 'Hall'), ('CAT009', 'Land'), ('CAT010', 'All Purpose Property')], default='CAT001', max_length=20, unique=True, verbose_name='category key'),
        ),
    ]
