# Generated by Django 4.0.3 on 2022-05-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_housetype_sharehouse'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyAreaLabel',
            new_name='PropertyMediaLabel',
        ),
        migrations.RenameField(
            model_name='commercialproperty',
            old_name='floor',
            new_name='floors',
        ),
        migrations.AddField(
            model_name='allpurposeproperty',
            name='has_parking_space',
            field=models.BooleanField(default=False, verbose_name='Does the property has parking space?'),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='has_parking_space',
            field=models.BooleanField(default=False, verbose_name='is the commercial property new?'),
        ),
        migrations.AddField(
            model_name='commercialproperty',
            name='is_multi_unit',
            field=models.BooleanField(blank=True, default=False, verbose_name='is multi unit?'),
        ),
        migrations.AddField(
            model_name='commercialpropertyunit',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hall',
            name='has_parking_space',
            field=models.BooleanField(default=False, verbose_name='Does the property has parking space?'),
        ),
        migrations.AddField(
            model_name='hall',
            name='number_of_parking_spaces',
            field=models.IntegerField(default=5, verbose_name='how many parking spaces the property has?'),
        ),
        migrations.AddField(
            model_name='office',
            name='has_parking_space',
            field=models.BooleanField(default=False, verbose_name='Does property has parking space?'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Does property has parking space?'),
        ),
    ]
