# Generated by Django 4.0.3 on 2022-05-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_rename_propertyarealabel_propertymedialabel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allpurposeproperty',
            old_name='vers_prop_description',
            new_name='all_purpose_property_description',
        ),
        migrations.RenameField(
            model_name='allpurposepropertyunit',
            old_name='vers_prop_unit_description',
            new_name='all_purpose_property_unit_description',
        ),
        migrations.RemoveField(
            model_name='allpurposeproperty',
            name='best_category_for',
        ),
        migrations.AddField(
            model_name='allpurposeproperty',
            name='best_for',
            field=models.TextField(blank=True, null=True, verbose_name='best for use'),
        ),
        migrations.AddField(
            model_name='allpurposeproperty',
            name='is_multi_unit',
            field=models.BooleanField(blank=True, default=False, verbose_name='is multi unit?'),
        ),
        migrations.AlterField(
            model_name='allpurposepropertyunit',
            name='floor',
            field=models.IntegerField(default=0, verbose_name='all purpose property unit floor level'),
        ),
    ]
