# Generated by Django 4.0.3 on 2022-05-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_rename_vers_prop_description_allpurposeproperty_all_purpose_property_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpurposeproperty',
            name='floors',
            field=models.IntegerField(default=0, verbose_name='all purpose property floor level'),
        ),
    ]
