# Generated by Django 4.0.3 on 2022-05-18 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_rename_propertymedialabel_propertyfilelabel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyvideo',
            name='label',
        ),
        migrations.RemoveField(
            model_name='propertyvirtualtour',
            name='label',
        ),
    ]
