# Generated by Django 4.0.3 on 2022-05-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_remove_propertyvideo_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvideo',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='video type'),
        ),
    ]
