# Generated by Django 4.0.3 on 2022-05-27 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_rename_point_of_interest_property_point_of_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.amenity')),
            ],
        ),
        # migrations.RemoveField(
        #     model_name='property',
        #     name='amenity',
        #     # field=models.ManyToManyField(blank=True, related_name='linked_properties', through='properties.PropertyAmenity', to='properties.amenity'),
        # ),
        migrations.AddField(
            model_name='property',
            name='amenity',
            field=models.ManyToManyField(related_name='linked_properties', through='PropertyAmenity', blank=True, to='properties.property'),
        ),
        migrations.AddField(
            model_name='propertyamenity',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
