# Generated by Django 4.0.3 on 2022-05-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_propertyamenity_alter_property_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenity',
        ),
    ]
