# Generated by Django 4.0.3 on 2022-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_remove_property_amenity'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='prop_amenity',
            field=models.ManyToManyField(blank=True, related_name='linked_properties', through='properties.PropertyAmenity', to='properties.amenity'),
        ),
    ]
