# Generated by Django 4.0.3 on 2022-05-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0026_property_prop_amenity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='prop_amenity',
            new_name='amenity',
        ),
    ]
