# Generated by Django 4.0.3 on 2022-05-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0029_rename_virtual_video_propertyvirtualtour_virtual_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='education_facility',
            field=models.ManyToManyField(blank=True, related_name='near_by_properties', through='properties.PropertyEduFacility', to='properties.educationfacility'),
        ),
        migrations.AlterField(
            model_name='property',
            name='point_of_interest',
            field=models.ManyToManyField(blank=True, related_name='near_by_properties', through='properties.PropertyPOI', to='properties.pointofinterest'),
        ),
        migrations.AlterField(
            model_name='property',
            name='transport_facility',
            field=models.ManyToManyField(blank=True, related_name='near_by_properties', through='properties.PropertyTransFacility', to='properties.transportfacility'),
        ),
    ]
