# Generated by Django 4.0.3 on 2022-06-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0032_propertycategoryamenity_propertycategory_amenities_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propertycategoryamenity',
            constraint=models.UniqueConstraint(fields=('property_category', 'amenity'), name='prop_cat_amenity_unique_constraint'),
        ),
    ]
