# Generated by Django 4.0.3 on 2022-06-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0033_propertycategoryamenity_prop_cat_amenity_unique_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='propertyamenity',
            constraint=models.UniqueConstraint(fields=('property', 'amenity'), name='property_amenity_unique_constraint'),
        ),
    ]
