# Generated by Django 4.0.3 on 2022-06-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0035_alter_rule_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='agent',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='agent who creates the apartment'),
        ),
    ]
