# Generated by Django 4.0.3 on 2022-06-07 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0037_alter_villa_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='agent',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='agent who creates the villa'),
        ),
        migrations.AlterField(
            model_name='allpurposeproperty',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='all_purpose_property', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apartment', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='commercialproperty',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_property', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='condominium',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='condominium', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='land',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='land', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='office',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='sharehouse',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share_house', to='properties.property', verbose_name='parent property'),
        ),
        migrations.AlterField(
            model_name='traditionalhouse',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traditional_house', to='properties.property', verbose_name='parent property'),
        ),
    ]
