# Generated by Django 4.0.3 on 2022-06-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0039_allpurposeproperty_agent_commercialproperty_agent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villa',
            old_name='total_coumpound_area',
            new_name='total_compound_area',
        ),
    ]
