# Generated by Django 4.0.3 on 2022-06-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_listingparameter_param_value_and_more'),
        ('properties', '0040_rename_total_coumpound_area_villa_total_compound_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingdiscountbycategory',
            name='listing_param',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_discount', to='systems.listingparameter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listingdiscountbycategoryhistory',
            name='listing_param',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='listing_discount_history', to='systems.listingparameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingpricebycategory',
            name='property_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='category_listing_price', to='properties.propertycategory'),
        ),
    ]
