# Generated by Django 4.0.3 on 2022-06-11 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_currency'),
        ('properties', '0041_listingdiscountbycategory_listing_param_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpricebycategory',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='systems.currency'),
        ),
    ]
