# Generated by Django 4.0.3 on 2022-06-12 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0042_listingpricebycategory_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingpricebycategory',
            name='property_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='listing_price', to='properties.propertycategory'),
        ),
    ]
