# Generated by Django 4.0.3 on 2022-06-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_mainlisting_listing_mode'),
        ('properties', '0043_alter_listingpricebycategory_property_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingpricebycategory',
            name='listing_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.listingtype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listingpricebycategory',
            name='property_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_price', to='properties.propertycategory'),
        ),
    ]
