# Generated by Django 4.0.3 on 2022-06-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0044_listingpricebycategory_listing_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingpricebycategory',
            name='listing_type',
        ),
    ]
