# Generated by Django 4.0.3 on 2022-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0046_listingpricebycategory_listing_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listingpricebycategory',
            constraint=models.UniqueConstraint(fields=('property_category', 'listing_type'), name='prop_listing_price_unique_together_constraint'),
        ),
    ]
