# Generated by Django 4.0.3 on 2022-06-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0047_listingpricebycategory_prop_listing_price_unique_together_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listingdiscountbycategory',
            constraint=models.UniqueConstraint(fields=('property_category', 'listing_param'), name='discount_unique_constraint'),
        ),
    ]
