# Generated by Django 4.0.3 on 2022-06-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0048_listingdiscountbycategory_discount_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingdiscountbycategory',
            name='param_value',
            field=models.CharField(default='', max_length=100, verbose_name='Listing parameter value'),
        ),
    ]
