# Generated by Django 4.0.3 on 2022-06-11 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0002_listingparameter_param_value_and_more'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiondiscount',
            name='listing_param',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='systems.listingparameter'),
            preserve_default=False,
        ),
    ]
