# Generated by Django 4.0.3 on 2022-06-11 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_rename_param_name_listingparameter_name_and_more'),
        ('subscriptions', '0002_subscriptiondiscount_listing_param'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='systems.currency'),
            preserve_default=False,
        ),
    ]
