# Generated by Django 4.0.3 on 2022-06-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptiondiscount',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionplan'),
        ),
    ]
