# Generated by Django 4.0.3 on 2022-05-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingparameter',
            name='param_value',
            field=models.CharField(default='', max_length=100, verbose_name='Listing parameter value'),
        ),
        migrations.AddField(
            model_name='systemparameter',
            name='param_value',
            field=models.CharField(default='', max_length=100, verbose_name='system parameter value'),
        ),
    ]
