# Generated by Django 4.0.3 on 2022-06-11 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0003_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listingparameter',
            old_name='param_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='listingparameter',
            old_name='param_value',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='systemparameter',
            old_name='param_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='systemparameter',
            old_name='param_value',
            new_name='value',
        ),
    ]
