# Generated by Django 4.0.3 on 2022-06-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0005_listingparameter_applied_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingparameter',
            name='value_type',
            field=models.CharField(choices=[('DAYS', 'Days'), ('LISTING_COUNT', 'Listing Count')], default='DAYS', max_length=100, verbose_name='Listing parameter value Type'),
        ),
        migrations.AlterField(
            model_name='listingparameter',
            name='name',
            field=models.CharField(choices=[('NEW_AGENT_PROMO', 'New Agent Promotion'), ('HOLIDAY_PROMOTION', 'Holiday Promotion')], default='NEW_AGENT_PROMO', max_length=100, verbose_name='listing parameter name'),
        ),
    ]
