# Generated by Django 4.0.3 on 2022-06-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0006_listingparameter_value_type_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listingparameter',
            constraint=models.UniqueConstraint(fields=('name', 'value_type', 'applied_to'), name='Listing_parameter_unique_constraint'),
        ),
    ]
