# Generated by Django 4.0.3 on 2022-07-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0010_alter_systemassetowner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemasset',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='system asset name'),
        ),
        migrations.AlterField(
            model_name='systemassetowner',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='name of owner of asset, (i.e. page, component)'),
        ),
    ]
