# Generated by Django 4.0.3 on 2022-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0011_alter_systemasset_name_alter_systemassetowner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemassetowner',
            name='name',
            field=models.CharField(choices=[('APARTMENT_PICTURE', 'Apartment Picture'), ('VILLA_PICTURE', 'Villa Picture'), ('CONDOMINIUM_PICTURE', 'Condominium Picture'), ('TRADITIONAL_HOUSE_PICTURE', 'Traditional House Picture'), ('SHARE_HOUSE_PICTURE', 'Share House Picture'), ('COMMERCIAL_PROPERTY_PICTURE', 'Commercial Property Picture'), ('OFFICE_PICTURE', 'Office Picture'), ('HALL_PICTURE', 'Hall Picture'), ('LAND_PICTURE', 'Land Picture'), ('ALL_PURPOSE_PROPERTY_PICTURE', 'All Purpose Property Picture'), ('LANDING_PAGE_SLIDER', 'Landing Page Slider')], max_length=250, unique=True, verbose_name='name of owner of asset, (i.e. page, component)'),
        ),
    ]
