# Generated by Django 4.0.3 on 2022-03-31 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_permission_role_systemadmingroup_systemadmin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_title', models.CharField(max_length=100, verbose_name='notification title')),
                ('notif_body', models.TextField(verbose_name='notification main message')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=30, verbose_name='channel name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='trigger name')),
                ('description', models.TextField(blank=True, null=True)),
                ('user_can_opt_out', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotifTargetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_name', models.CharField(max_length=50, unique=True, verbose_name='trigger name')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('read', models.BooleanField(default=False)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifTriggerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_out', models.BooleanField(default=False)),
                ('setting_made_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('trigger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtrigger', verbose_name='notification trigger')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, verbose_name='notification template name')),
                ('template_path', models.CharField(max_length=250, verbose_name='notification template path')),
                ('notif_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.ManyToManyField(to='notifications.notificationchannel', verbose_name='notification channel to be used'),
        ),
        migrations.AddField(
            model_name='notification',
            name='target_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notiftargettype', verbose_name='notification target type'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ManyToManyField(through='notifications.UserNotification', to=settings.AUTH_USER_MODEL, verbose_name='users to sent to'),
        ),
        migrations.CreateModel(
            name='NotifChannelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opt_out', models.BooleanField(default=False, verbose_name='opt this channel out')),
                ('set_on', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('notif_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationchannel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
